// Generated by CoffeeScript 1.8.0
var concat, gulp;

gulp = require('gulp');

concat = require('gulp-concat');

gulp.task('default', ['js']);

gulp.task('js', function() {
  return gulp.src(['*.js', 'durandal/**/*.js']).pipe(concat('dist.js')).pipe(gulp.dest('./'));
});
