// Generated by CoffeeScript 1.7.1
(function() {
  define('transitions/forward', ['durandal/system', 'odo/durandal/transitions/velocity'], function(system, Velocity) {
    return function(context) {
      system.extend(context, {
        inAnimation: 'slideInRight',
        outAnimation: 'slideOutLeft'
      });
      return new Velocity().create(context);
    };
  });

}).call(this);
