// Generated by CoffeeScript 1.7.1
(function() {
  define('text!components/dialog.html', [], function() {
    return "<div class=\"modal-dialog animated\" data-bind=\"css: { shake: shouldShake }\">\n	<!-- ko compose: composeOptions --><!-- /ko -->\n</div>";
  });

}).call(this);
