// Generated by CoffeeScript 1.7.1
(function() {
  define('text!components/wizard.html', [], function() {
    return '<div class="wizard" data-bind="compose: composeOptions"></div>';
  });

}).call(this);
