// Generated by CoffeeScript 1.7.1
(function() {
  define('odo/durandal/plugins/bootstrap', ['knockout', 'jquery'], function(ko, $) {
    return ko.bindingHandlers.popover = {
      init: function(element, valueAccessor) {
        var options;
        options = ko.unwrap(valueAccessor());
        return $(element).popover(options);
      }
    };
  });

}).call(this);
