// Generated by CoffeeScript 1.7.1
(function() {
  define('odo/durandal/plugins/marked', ['knockout', 'marked'], function(ko, marked) {
    return ko.bindingHandlers.marked = {
      init: function() {
        return {
          'controlsDescendantBindings': true
        };
      },
      update: function(element, valueAccessor) {
        return ko.utils.setHtml(element, marked(ko.utils.unwrapObservable(valueAccessor())));
      }
    };
  });

}).call(this);
