// Generated by CoffeeScript 1.7.1
(function() {
  define('odo/durandal/plugins/validation', ['knockout', 'ko.validation'], function(ko) {
    return ko.validation.configure({
      registerExtenders: true,
      parseInputAttributes: true,
      insertMessages: false,
      errorMessageClass: 'help-block',
      errorElementClass: 'has-error'
    });
  });

}).call(this);
