// Generated by CoffeeScript 1.7.1
(function() {
  define('odo/durandal/plugins/viewLocator', ['durandal/viewLocator'], function(locator) {
    return locator.useConvention('views');
  });

}).call(this);
